// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cqhTB1fsvFgOMQfMl7nAiu4npchzq2s',
    appId: '1:1027337731912:web:ebace1b2563d6fbb027d7d',
    messagingSenderId: '1027337731912',
    projectId: 'gemini-demo-3f8d2',
    authDomain: 'gemini-demo-3f8d2.firebaseapp.com',
    storageBucket: 'gemini-demo-3f8d2.appspot.com',
    measurementId: 'G-5H1785JH4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPsTNEBqPGA1zc0tobjW6dl0_uTMeM80',
    appId: '1:1027337731912:android:769d354258215970027d7d',
    messagingSenderId: '1027337731912',
    projectId: 'gemini-demo-3f8d2',
    storageBucket: 'gemini-demo-3f8d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqO6DGxtv2Bci7mRhU3bTqidoW-e4ZSgM',
    appId: '1:1027337731912:ios:f4c23fa131689ed8027d7d',
    messagingSenderId: '1027337731912',
    projectId: 'gemini-demo-3f8d2',
    storageBucket: 'gemini-demo-3f8d2.appspot.com',
    iosBundleId: 'com.example.geminiDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqO6DGxtv2Bci7mRhU3bTqidoW-e4ZSgM',
    appId: '1:1027337731912:ios:91f64c242d4ee7f7027d7d',
    messagingSenderId: '1027337731912',
    projectId: 'gemini-demo-3f8d2',
    storageBucket: 'gemini-demo-3f8d2.appspot.com',
    iosBundleId: 'com.example.geminiDemo.RunnerTests',
  );
}
